title: Jwan
#logo: /assets/img/logo.png
description: Meet Jwan, a junior cybersecurity who outsmarts malware while you’re still figuring out your router!
#show_downloads: false
#google_analytics:
theme: jekyll-theme-cayman
